<?php
include('config.php');
if ($_POST["password"] == "PA<4pN7P8k4xU?q"){

$site2 = mysql_query("SELECT * FROM `users` WHERE `login`='{$_POST["title1"]}'");
$userr = mysql_fetch_object($site2);

mysql_query("UPDATE `users` SET `coins`=`coins`+'{$_POST["title2"]}', `pr`=`pr`+'{$_POST["title3"]}', `bought`= '1' WHERE `id`='{$userr->id}'");
mysql_query("INSERT INTO statistics (user_id,date,coins_gained,fb_like,log,page) VALUES ({$data->id},NOW(),{$coinsadded},1,'<b style=\"color:green;\">Bought Points</b>','kyr360.php')");
mysql_query("INSERT INTO `orders` (user_id, points, date, price) VALUES('{$userr->id}', '{$_POST["title4"]}', NOW(), '{$_POST["title5"]}' ) ");

if ($_POST["title4"] > 0) {
mysql_query("INSERT INTO `fakeorders` (login, country, money, points, date) VALUES('{$userr->login}', '{$userr->country}', '{$_POST["title5"]}', '{$_POST["title2"]}', NOW() ) ");
}

if ($_POST["title3"] > 0) {
$msgggtitle = "+" . $_POST["title3"] . " hours of VIP Membership.";
} else {
$msgggtitle = "+" . $_POST["title2"] . " Points added to your Account Balance.";
}

echo "Done.</br>";
echo $userr->email;
echo "</br>";
echo $userr->country;
echo "-----------------</br></br>";


// Send Email #1 to PayPal paid:

// Send another email to confirm support.
// To email address
$email = $_POST["title6"];
$email_name = $_POST["title7"];

// From email address
$from = 'afonsolgfaria@gmail.com';
$from_name = 'LikesPlanet.com';

// The message
$subject = "LikesPlanet.com | " . $msgggtitle;

$message = "Hello ".$email_name." !

Your Order/Payment has been processed.

Thank you

http://likesplanet.com/
";

$message_html = "<html><body><p>
</p><font color='#8A2BE2' size=3>
Hello ".$email_name."
<br /><br /><br /><br />
<font style='BACKGROUND-COLOR: yellow' size=4><b>
" . $msgggtitle . "
</b></font>
<br /><br /><br /><br /><br />
--------------------------------------------
<br />Thanks for using LikesPlanet network.
<br />
<br />Kind Regards,
<br />LikesPlanet team.
<br />
<br /> * This is Automatic email generated by computer. No need to reply.
</body></html>";

/***********************************************/
/* No need to modify anything down here */
/* Note that these are needed to send the mail */
/***********************************************/
// Generate text + html version
$random_hash = md5(date("r", time()));

$mailmessage = "
--PHP-alt-".$random_hash."
Content-Type: text/plain; charset=\"iso-8859-1\"
Content-Transfer-Encoding: 7bit

$message

--PHP-alt-".$random_hash."
Content-Type: text/html; charset=\"iso-8859-1\"
Content-Transfer-Encoding: 7bit

$message_html

--PHP-alt-".$random_hash."--
";

// Headers
// To send HTML mail, the Content-type header must be set
$headers = "From: ".$from_name." <".$from.">" . "\r\n";
$headers .= "Reply-To: ".$from_name." <".$from.">" . "\r\n";
$headers .= "Date: ".date("r") . "\r\n";

// Additional headers
$headers .= "MIME-Version: 1.0" . "\r\n";
$headers .= "Content-Type: multipart/alternative; boundary=\"PHP-alt-" . $random_hash . "\"\r\n";
$headers .= "Message-Id: <" . md5(uniqid(microtime())) . "@" . $_SERVER["SERVER_NAME"] . ">\r\n";

// Send the mail
mail($email, $subject, $mailmessage, $headers);






// Send Email #2 to Registered paid:

// Send another email to confirm support.
// To email address
$email = $userr->email;
$email_name = $_POST["title7"];

// From email address
$from = 'likesplanet.com@gmail.com';
$from_name = 'LikesPlanet.com';

// The message
$subject = "LikesPlanet.com | " . $msgggtitle;

$message = "Hello ".$email_name." !

Your Order/Payment has been processed.

Thank you

http://likesplanet.com/
";

$message_html = "<html><body><p>
</p><font color='#8A2BE2' size=3>
Hello ".$email_name."
<br /><br /><br /><br />
<font style='BACKGROUND-COLOR: yellow' size=4><b>
" . $msgggtitle . "
</b></font>
<br /><br /><br /><br /><br />
--------------------------------------------
<br />Thanks for using LikesPlanet network.
<br />
<br />Kind Regards,
<br />LikesPlanet team.
<br />
<br /> * This is Automatic email generated by computer. No need to reply.
</body></html>";

/***********************************************/
/* No need to modify anything down here */
/* Note that these are needed to send the mail */
/***********************************************/
// Generate text + html version
$random_hash = md5(date("r", time()));

$mailmessage = "
--PHP-alt-".$random_hash."
Content-Type: text/plain; charset=\"iso-8859-1\"
Content-Transfer-Encoding: 7bit

$message

--PHP-alt-".$random_hash."
Content-Type: text/html; charset=\"iso-8859-1\"
Content-Transfer-Encoding: 7bit

$message_html

--PHP-alt-".$random_hash."--
";

// Headers
// To send HTML mail, the Content-type header must be set
$headers = "From: ".$from_name." <".$from.">" . "\r\n";
$headers .= "Reply-To: ".$from_name." <".$from.">" . "\r\n";
$headers .= "Date: ".date("r") . "\r\n";

// Additional headers
$headers .= "MIME-Version: 1.0" . "\r\n";
$headers .= "Content-Type: multipart/alternative; boundary=\"PHP-alt-" . $random_hash . "\"\r\n";
$headers .= "Message-Id: <" . md5(uniqid(microtime())) . "@" . $_SERVER["SERVER_NAME"] . ">\r\n";

// Send the mail
mail($email, $subject, $mailmessage, $headers);







}
else{
echo "Password Needed !";
}
?>